### ISSUE TITLE
Couldn't resolve field 'edges' to GraphQL::Relay::RelationConnection

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-relay-ruby#25]
Hello @rmosolgo 

Getting following error when fetching next set of records using `first: 10` parameter in Relay. 

### Error when fetching next posts (pagination)
``` ruby
 RuntimeError (Couldn't resolve field 'edges' to GraphQL::Relay::RelationConnection '#<GraphQL::Relay::RelationConnection:0x007ff75a0ff150>' (resulted in undefined method `engine' for #<Arel::Table:0x007ff759587a20>)):
11:16:11 web.1    |   app/controllers/graphql_controller.rb:8:in `create'
11:16:11 web.1    |   lib/graphql_reloader.rb:10:in `call'
```
This works in previous versions of the Gem (0.10.8), but not in the recent version. 

### Gems used
``` bash
Latest version of graphql and graphql-relay
Rails version 5 beta
```
